name: Deploy

on:
  push:
    tag:
      - 'v*'

jobs:
  deploy:
    name: Deploy to GAS
    runs-on: ubuntu-latest
    environment: development
    env:
      CLASP_SCRIPT_ID: ${{ secrets.CLASP_SCRIPT_ID }}
    working-directory: gas
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Create .env file
        shell: bash
        run: |
          cat > .clasp.json <<EOF
          {
            "scriptId": "${{ env.CLASP_SCRIPT_ID }}",
            "rootDir": "dist"
          }
          EOF
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node
        env:
          cache-name: cache-node
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cache-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cache-node-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-
      - name: Install node modules
        if: ${{ steps.cache-node.outputs.cache-hit != 'true' }}
        run: pnpm i
      - name: Build
        run: pnpm run deploy
